version: '3.9'

services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'future-space'
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build: .
    depends_on:
      - db
    ports:
      - '3333:3333'

volumes:
  data:
